OHSUCMP/coach

docker-compose.override.yml, env.sample
I missed thse configuration bits when I merged:
- Add docker-compose service for CQF Ruler
- Add VSAC API key to env.sample
=> Add CQFRuler compose config and update env.sample

README.md, src/main/resources/static/css/home.css, src/main/resources/static/js/bpchart.js, src/main/resources/static/js/home.js, src/main/resources/templates/home.mustache
Make the chart average calculation more closely resemble the recommendation:
- Calculation is static and based on the recent BP set
- Replace "2 months" with "Recent" that displays the BP set, falling back on 2 months if no set exists
- Shade the portion of the graph corresponding to the BP set
=> Chart Average Calculation

README.md
Add information about permissions required for logging to `README.md`.
=> Add Permission Information to README.md

src/main/resources/static/js/recommendations.js
Two class declarations on the element. The second was ignored, and this is the class the datepicker keys off of.
=> #82: Fix datepicker in goal setting.

README.md, docker-compose.override.yml, src/main/resources/static/js/home.js
The warning about two high BPs should only appear when both have been measured in the last 14 days. Because of the vagaries of timezones, the comparison between "today" and the BP may not be exact, but this code will at least confirm that they are both within AROUND 14 days old.
=> #91: Check dates when there are two high BPs

cerner-config/application.properties, epic-config/application.properties, logica-config/application.properties, meld-config/application.properties, src/main/resources/application.properties
Update all configurations so every instance receives the recommendations in a consistent order that highlights safety measures and then presents additional information in a logical order.
=> Offer the recommendations in a consistent order.

src/main/java/edu/ohsu/cmp/coach/controller/HomeController.java, src/main/java/edu/ohsu/cmp/coach/entity/RedcapParticipantInfo.java
Forward participants without an information sheet complete back to that survey.
=> #113: Handle incomplete information sheet.

src/main/java/edu/ohsu/cmp/coach/exception/REDCapException.java, src/main/java/edu/ohsu/cmp/coach/service/REDCapService.java, src/main/resources/templates/fhir-complete-handshake.mustache
Provide a custom message to the user when REDCap is down.
=> #116: Handle REDCap downtime.

src/main/java/edu/ohsu/cmp/coach/controller/ResourcesController.java, src/main/java/edu/ohsu/cmp/coach/layout/LayoutAdvice.java, src/main/resources/static/css/coach.css, src/main/resources/templates/faq.mustache, src/main/resources/templates/layout/footer.mustache, src/main/resources/templates/layout/header.mustache
Add FAQ page and copyright in footer
=> #45: FAQ Page

pom.xml, src/main/java/edu/ohsu/cmp/coach/service/EHRService.java
FYI @mattStorer I will be testing this fix on POC
=> #114: Filter out Epic OperationOutcome from Conditions query.

cerner-config/application.properties, epic-config/application.properties, logica-config/application.properties, meld-config/application.properties, src/main/java/edu/ohsu/cmp/coach/layout/LayoutAdvice.java, src/main/resources/application.properties, src/main/resources/templates/layout/footer.mustache
Allows us to see which version is deployed in each environment.
Note the two additions to application.properties.
=> #125: Add project version to footer

src/main/java/edu/ohsu/cmp/coach/controller/HomeController.java, src/main/java/edu/ohsu/cmp/coach/entity/RandomizationGroup.java, src/main/java/edu/ohsu/cmp/coach/service/RecommendationService.java, src/main/java/edu/ohsu/cmp/coach/workspace/UserWorkspace.java, src/main/resources/application.properties, src/main/resources/static/js/home.js, src/main/resources/templates/home.mustache
Changes to display for the control group
=> #64: Control Group Display

src/main/resources/templates/vitals.mustache
=> #145: Fix error preventing BP entry for patients with no readings.

src/main/java/edu/ohsu/cmp/coach/entity/RedcapParticipantInfo.java, src/main/java/edu/ohsu/cmp/coach/service/REDCapService.java
Provide the randomization date in RedcapParticipantInfo so it can be used to calculate dates for OMRON integration.
=> #151: Add randomizationDate to RedcapParticipantInfo

src/main/java/edu/ohsu/cmp/coach/controller/HomeController.java, src/main/java/edu/ohsu/cmp/coach/service/PatientService.java, src/main/java/edu/ohsu/cmp/coach/service/REDCapService.java
More logging of the participant creation process and REDCap workflow to better understand the errors we're seeing.
=> #163: Logging REDCap workflow.

src/main/java/edu/ohsu/cmp/coach/service/REDCapService.java
The participant info form in REDCap has a new date field study staff needs.
=> #166: Populate date when creating participant in REDCap.

src/main/java/edu/ohsu/cmp/coach/GlobalExceptionHandler.java, src/main/java/edu/ohsu/cmp/coach/controller/GoalsController.java, src/main/java/edu/ohsu/cmp/coach/controller/HomeController.java, src/main/java/edu/ohsu/cmp/coach/controller/VitalsController.java, src/main/java/edu/ohsu/cmp/coach/workspace/UserWorkspace.java, src/main/resources/static/js/goals.js, src/main/resources/static/js/home.js, src/main/resources/static/js/layout.js, src/main/resources/static/js/recommendations.js, src/main/resources/static/js/vitals.js, src/main/resources/templates/fhir-complete-handshake.mustache, src/main/resources/templates/home.mustache, src/main/resources/templates/launch-ehr.mustache, src/main/resources/templates/launch-patient.mustache, src/main/resources/templates/layout/footer.mustache, src/main/resources/templates/vitals.mustache
improved error handling and communication of errors to users if something they do goes wrong somehow.
=> #167: complete UI error reporting logic

src/main/java/edu/ohsu/cmp/coach/entity/RedcapParticipantInfo.java, src/main/java/edu/ohsu/cmp/coach/service/REDCapService.java
Ensure VUMC participants have also consented to the additional HIPAA requirement.
=> #191: Add HIPAA consent to VUMC REDCap workflow.

src/main/resources/static/css/home.css, src/main/resources/static/js/home.js, src/main/resources/templates/home.mustache
Made clickable and added a box-shadow so it's more obvious.
=> #208: Make the OMRON sync alert box clickable.

src/main/resources/db/migration/sqlserver/V20230921125600__baseline_migration.sql, src/main/resources/db/migration/sqlserver/V20231011145753__hypotension_ae.sql, src/main/resources/db/migration/sqlserver/V20231107084100__remove_consent_study_class.sql, src/main/resources/db/migration/sqlserver/V20231222133444__add_bpGoalUpdated_flag.sql, src/main/resources/db/migration/sqlserver/V20240123105612__audit.sql, src/main/resources/db/migration/sqlserver/V20240723131642__add_end_of_study_flag.sql
there were some lines of SQL in the SQL Server Flyway database migrations that weren't executing correctly.  testing, we definitely didn't test all of these ourselves.  I've now gone through and tested each of these migrations and they all execute in SQL Server, so we should be good.
=> #226 - updated SQL Server migrations

.github/workflows/codeql.yml
created codeql.yml to facilitate building with Java 17, since autodetection of Java language level doesn't seem to work
=> #243 - Create codeql.yml

.dockerignore, Dockerfile
PR from @preston for multiplatform Docker build
=> Putting application build inside image build as expected.
